//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulasPruevas0102.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class asignacionEntities : DbContext
    {
        public asignacionEntities()
            : base("name=asignacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<BloqueHora> BloqueHoras { get; set; }
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<CorreoUsuario> CorreoUsuarios { get; set; }
        public virtual DbSet<Espacio> Espacios { get; set; }
        public virtual DbSet<Facultad> Facultads { get; set; }
        public virtual DbSet<Grupo> Grupoes { get; set; }
        public virtual DbSet<HorariosFijo> HorariosFijos { get; set; }
        public virtual DbSet<InscripcionMateria> InscripcionMaterias { get; set; }
        public virtual DbSet<logueo> logueos { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<TelefonoUsuario> TelefonoUsuarios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
