//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulasPruevas0102.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreoUsuario
    {
        public int IdCorreo { get; set; }
        public int IdUsuario { get; set; }
        public string Correo { get; set; }
        public int Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
