//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAulas.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AulaBaseEntities : DbContext
    {
        public AulaBaseEntities()
            : base("name=AulaBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<BloqueHoras> BloqueHoras { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<CorreoUsuario> CorreoUsuario { get; set; }
        public virtual DbSet<Espacio> Espacio { get; set; }
        public virtual DbSet<Facultad> Facultad { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<HorariosFijos> HorariosFijos { get; set; }
        public virtual DbSet<InscripcionMateria> InscripcionMateria { get; set; }
        public virtual DbSet<Logueo> Logueo { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TelefonoUsuario> TelefonoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
