//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAulas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int IdReserva { get; set; }
        public string CodigoReservante { get; set; }
        public Nullable<int> IdEspacio { get; set; }
        public Nullable<int> IdBloque { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Confirmacion { get; set; }
        public int Estado { get; set; }
    
        public virtual BloqueHoras BloqueHoras { get; set; }
        public virtual Espacio Espacio { get; set; }
    }
}
