//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorariosFijos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HorariosFijos()
        {
            this.Horario = new HashSet<Horario>();
        }
    
        public int IdHorarioFijo { get; set; }
        public Nullable<int> IdMateria { get; set; }
        public Nullable<int> IdEspacio { get; set; }
        public int Estado { get; set; }
    
        public virtual Espacio Espacio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
