//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionMateria
    {
        public int IdInscripcion { get; set; }
        public string IdInscrito { get; set; }
        public Nullable<int> IdMateria { get; set; }
        public int Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
